"""
FNO for Linearized Poisson-Boltzmann Screened Electrostatic Energy
==================================================================

We train a 3-D Fourier Neural Operator (FNO) to predict a scalar screened
electrostatic energy from volumetric fields relevant to continuum
electrostatics: the charge density :math:`\\rho(\\mathbf{r})` and the inverse
Debye length :math:`\\kappa`.

This is a natural application for neural operators:

1. The input is already a continuous 3-D field.
2. The target comes from a PDE solve, not from an arbitrary tabular label.
3. Resolution invariance matters because the same physical system may be
   discretized on different voxel grids in real electrostatics workflows.

To keep the example self-contained, ground-truth labels are generated by
solving a synthetic *linearized Poisson-Boltzmann* problem in Fourier space on
a periodic box with homogeneous dielectric:

.. math::

   \\left(-\\nabla^2 + \\kappa^2\\right)\\varphi(\\mathbf{r})
   = \\rho(\\mathbf{r}) / \\varepsilon

and then computing the screened electrostatic energy

.. math::

   E_\\mathrm{el} = \\tfrac{1}{2}\\int \\rho(\\mathbf{r})\\,\\varphi(\\mathbf{r})\\,d^3r.

We train on a coarse grid (16³) and evaluate on the *same latent test systems*
discretized at both 16³ and 24³, which gives a direct resolution-invariance
check rather than comparing unrelated random samples.
"""

# %%
# .. raw:: html
#
#    <div style="margin-top: 3em;"></div>
#
# Import dependencies
# -------------------
# We use PyTorch for synthetic-data generation and Fourier-space solves, and
# ``neuralop`` for the FNO model, trainer, and resolution-invariant readout.

import math
import sys

import matplotlib.pyplot as plt
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset

from neuralop import Trainer
from neuralop.data.transforms.data_processors import DefaultDataProcessor
from neuralop.models import FNO, ResolutionInvariantReadout
from neuralop.training import AdamW
from neuralop.utils import count_model_params

device = "cuda" if torch.cuda.is_available() else "cpu"


# %%
# .. raw:: html
#
#    <div style="margin-top: 3em;"></div>
#
# Synthetic linearized-PB dataset
# -------------------------------
# Continuum electrostatics is widely used in protein chemistry and drug design
# to estimate electrostatic contributions to solvation, pKa shifts, and binding.
# The *linearized* Poisson-Boltzmann equation is a standard screened-electrostatics
# model.  In this example we use a deliberately simplified setting: homogeneous
# dielectric, periodic boundary conditions, and a spatially constant screening
# parameter for each sample. In that setting the Fourier-space solution is analytic:
#
# .. math::
#
#    \hat{\varphi}(\mathbf{k}) =
#    \frac{\hat{\rho}(\mathbf{k})}
#         {\varepsilon (|\mathbf{k}|^2 + \kappa^2)}.
#
# We use this exact spectral solve to generate labels for random mixtures of
# Gaussian partial charges.  The charge density and screening field are the
# model inputs, while the scalar screened electrostatic energy is the target.

EPSILON = 80.0  # solvent dielectric
BOX_SIZE = 8.0  # Angstrom
RHO_SIGMA = 0.35  # Angstrom
N_TRAIN = 16
N_TEST_HI = 24
N_TRAIN_SAMPLES = 192
N_TEST_SAMPLES = 48
N_CHARGES_RANGE = (3, 6)


def _grid_coordinates(n: int, box_size: float) -> torch.Tensor:
    """Return a centered (n, n, n, 3) coordinate grid on a periodic box."""
    h = box_size / n
    coords_1d = (torch.arange(n, dtype=torch.float32) - n / 2 + 0.5) * h
    gz, gy, gx = torch.meshgrid(coords_1d, coords_1d, coords_1d, indexing="ij")
    return torch.stack([gx, gy, gz], dim=-1)


def _make_charge_density(
    grid: torch.Tensor,
    positions: torch.Tensor,
    charges: torch.Tensor,
    sigma: float,
) -> torch.Tensor:
    """Build a smooth charge density from Gaussian partial charges."""
    delta = grid.unsqueeze(-2) - positions.view(1, 1, 1, -1, 3)
    r2 = (delta**2).sum(dim=-1)
    norm = 1.0 / ((2.0 * math.pi * sigma**2) ** 1.5)
    gaussians = torch.exp(-r2 / (2.0 * sigma**2)) * norm
    return (gaussians * charges.view(1, 1, 1, -1)).sum(dim=-1)


def _spectral_k2(n: int, box_size: float) -> torch.Tensor:
    """Return the squared wave-number tensor for a periodic cube."""
    h = box_size / n
    freqs = 2.0 * math.pi * torch.fft.fftfreq(n, d=h)
    kz, ky, kx = torch.meshgrid(freqs, freqs, freqs, indexing="ij")
    return kx**2 + ky**2 + kz**2


def _solve_linearized_pb(
    rho: torch.Tensor, kappa: float, epsilon: float, k2: torch.Tensor
) -> torch.Tensor:
    """Solve (-Δ + kappa^2) phi = rho / epsilon on a periodic cube."""
    rho_hat = torch.fft.fftn(rho)
    phi_hat = rho_hat / (epsilon * (k2 + kappa**2))
    return torch.fft.ifftn(phi_hat).real


def _electrostatic_energy(
    rho: torch.Tensor, phi: torch.Tensor, box_size: float
) -> float:
    """Return 0.5 * integral rho(r) * phi(r) d^3r."""
    return float(0.5 * (rho * phi).mean() * (box_size**3))


def _sample_latent_systems(n_samples: int, seed: int) -> list:
    """Sample latent charge configurations shared across resolutions."""
    gen = torch.Generator()
    gen.manual_seed(seed)

    systems = []
    for _ in range(n_samples):
        n_charges = int(
            torch.randint(
                low=N_CHARGES_RANGE[0],
                high=N_CHARGES_RANGE[1] + 1,
                size=(1,),
                generator=gen,
            ).item()
        )

        # Keep charges away from the periodic boundary so the localized density
        # looks molecule-like instead of wrapping around the box.
        positions = torch.empty(n_charges, 3).uniform_(-2.0, 2.0, generator=gen)
        charges = torch.empty(n_charges).uniform_(-1.0, 1.0, generator=gen)
        charges -= charges.mean()
        # Use a deliberately broad synthetic screening range to make the
        # operator-learning task diverse; realistic biomolecular screening is
        # often weaker than this.
        kappa = float(torch.empty(1).uniform_(0.4, 1.2, generator=gen).item())
        systems.append({"positions": positions, "charges": charges, "kappa": kappa})
    return systems


class LinearPBDataset(Dataset):
    """Exact spectral linearized-PB labels on a fixed-resolution voxel grid."""

    def __init__(self, systems: list, n_pts: int, box_size: float):
        self.systems = systems
        self.n_pts = n_pts
        self.box_size = box_size
        self.grid = _grid_coordinates(n_pts, box_size)
        self.k2 = _spectral_k2(n_pts, box_size)

        xs, ys, phis = [], [], []
        for system in systems:
            rho = _make_charge_density(
                self.grid, system["positions"], system["charges"], sigma=RHO_SIGMA
            )
            phi = _solve_linearized_pb(
                rho=rho,
                kappa=system["kappa"],
                epsilon=EPSILON,
                k2=self.k2,
            )
            kappa_field = torch.full_like(rho, system["kappa"])
            xs.append(torch.stack([rho, kappa_field], dim=0))
            ys.append(_electrostatic_energy(rho, phi, box_size))
            phis.append(phi)

        self.x = torch.stack(xs)
        self.y = torch.tensor(ys, dtype=torch.float32).unsqueeze(1)
        self.phi = torch.stack(phis)

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return {"x": self.x[idx], "y": self.y[idx]}


train_systems = _sample_latent_systems(N_TRAIN_SAMPLES, seed=0)
test_systems = _sample_latent_systems(N_TEST_SAMPLES, seed=1)

train_dataset = LinearPBDataset(train_systems, n_pts=N_TRAIN, box_size=BOX_SIZE)
test_dataset_16 = LinearPBDataset(test_systems, n_pts=N_TRAIN, box_size=BOX_SIZE)
test_dataset_24 = LinearPBDataset(test_systems, n_pts=N_TEST_HI, box_size=BOX_SIZE)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loaders = {
    N_TRAIN: DataLoader(test_dataset_16, batch_size=16),
    N_TEST_HI: DataLoader(test_dataset_24, batch_size=16),
}
data_processor = DefaultDataProcessor().to(device)


# %%
# .. raw:: html
#
#    <div style="margin-top: 3em;"></div>
#
# Visualizing the field solve
# --------------------------
# For one test system, we show the charge density and the corresponding exact
# linearized-PB potential obtained by the Fourier-space solver.  This makes the
# operator-learning aspect explicit: the scalar energy label is derived from a
# nontrivial field solve, not a hand-coded molecular descriptor.

fig, axes = plt.subplots(2, 2, figsize=(7, 6))
for row, dataset in enumerate([test_dataset_16, test_dataset_24]):
    n = dataset.n_pts
    sl = n // 2
    rho_sl = dataset.x[0, 0, sl].numpy()
    phi_sl = dataset.phi[0, sl].numpy()
    im0 = axes[row, 0].imshow(rho_sl, cmap="RdBu_r")
    axes[row, 0].set_title(f"{n}³ grid: rho slice")
    plt.colorbar(im0, ax=axes[row, 0])
    im1 = axes[row, 1].imshow(phi_sl, cmap="viridis")
    axes[row, 1].set_title(f"{n}³ grid: exact phi slice")
    plt.colorbar(im1, ax=axes[row, 1])
    for ax in axes[row]:
        ax.set_xticks([])
        ax.set_yticks([])
fig.suptitle("Same latent test system at two voxel resolutions", y=0.98)
plt.tight_layout()
fig.show()


# %%
# .. raw:: html
#
#    <div style="margin-top: 3em;"></div>
#
# Building the FNO model
# ----------------------
# The model consumes two 3-D input channels:
#
# * :math:`\\rho(\\mathbf{r})` — charge density
# * :math:`\\kappa(\\mathbf{r})` — inverse Debye length
#   (constant within each synthetic sample)
#
# It returns a scalar screened electrostatic energy via
# :class:`~neuralop.models.ResolutionInvariantReadout`.
# The readout computes a grid-independent physical integral by applying
# ``mean(field) × L³`` before the final head.

FNO_OUT_CHANNELS = 8

model = FNO(
    n_modes=(4, 4, 4),
    in_channels=2,
    out_channels=FNO_OUT_CHANNELS,
    hidden_channels=20,
    n_layers=4,
    projection_channel_ratio=2,
    readout=ResolutionInvariantReadout(
        in_channels=FNO_OUT_CHANNELS,
        out_dim=1,
        reduce="integral",
        measure_per_dim=BOX_SIZE,
        head="mlp",
        mlp_hidden_dim=32,
    ),
).to(device)

n_params = count_model_params(model)
print(f"\nModel has {n_params} parameters.")
sys.stdout.flush()


# %%
# .. raw:: html
#
#    <div style="margin-top: 3em;"></div>
#
# Loss function and training
# --------------------------
# The target is a scalar screened electrostatic energy, so we optimize MSE.


class EnergyLoss(nn.Module):
    """Sum of squared errors between predicted and exact linearized-PB screened energies."""

    def forward(self, out, y, **kwargs):
        return torch.sum((out - y) ** 2)


energy_loss = EnergyLoss()

N_EPOCHS = 12
optimizer = AdamW(model.parameters(), lr=5e-3, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=N_EPOCHS)

trainer = Trainer(
    model=model,
    n_epochs=N_EPOCHS,
    device=device,
    data_processor=data_processor,
    wandb_log=False,
    eval_interval=4,
    use_distributed=False,
    verbose=True,
)

trainer.train(
    train_loader=train_loader,
    test_loaders=test_loaders,
    optimizer=optimizer,
    scheduler=scheduler,
    regularizer=False,
    training_loss=energy_loss,
    eval_losses={"energy_mse": energy_loss},
)


# %%
# .. raw:: html
#
#    <div style="margin-top: 3em;"></div>
#
# Predicted vs true energy at both resolutions
# -------------------------------------------
# We evaluate the same underlying test systems on both the training grid (16³)
# and an unseen finer grid (24³).  This isolates resolution effects from sample
# variation.

model.eval()
results = {}
for res, loader in sorted(test_loaders.items()):
    preds, trues = [], []
    with torch.no_grad():
        for batch in loader:
            batch = data_processor.preprocess(batch)
            out = model(batch["x"])
            preds.append(out.cpu())
            trues.append(batch["y"].cpu())
    preds = torch.cat(preds).squeeze(1).numpy()
    trues = torch.cat(trues).squeeze(1).numpy()
    results[res] = (trues, preds)
    h_val = BOX_SIZE / res
    mse = float(((preds - trues) ** 2).mean())
    print(f"Resolution {res}³  (h = {h_val:.3f} Å)  MSE = {mse:.4f}")


# %%
# .. raw:: html
#
#    <div style="margin-top: 3em;"></div>
#
# Resolution-paired comparison
# ----------------------------
# Because both test sets come from the same latent systems, we can compare
# coarse-grid and fine-grid predictions *sample by sample*.

preds_16 = results[N_TRAIN][1]
preds_24 = results[N_TEST_HI][1]

fig, axes = plt.subplots(1, 2, figsize=(9, 4))

for ax, (res, (true_vals, pred_vals)) in zip(axes, sorted(results.items())):
    mse = float(((pred_vals - true_vals) ** 2).mean())
    lims = [
        min(true_vals.min(), pred_vals.min()) - 0.02,
        max(true_vals.max(), pred_vals.max()) + 0.02,
    ]
    ax.scatter(true_vals, pred_vals, s=12, alpha=0.6)
    ax.plot(lims, lims, "r--", lw=1, label="perfect")
    ax.set_xlabel("Exact screened energy")
    ax.set_ylabel("FNO prediction")
    ax.set_title(f"{res}³ grid\nMSE = {mse:.4f}")
    ax.legend(fontsize=8)

plt.tight_layout()
fig.show()


# %%
# .. raw:: html
#
#    <div style="margin-top: 3em;"></div>
#
# Direct cross-resolution consistency
# -----------------------------------
# Finally, we compare the model's prediction for each test system at 16³ and
# 24³.  Small scatter around the diagonal indicates that one trained model can
# serve multiple electrostatics grid resolutions without re-fitting.

fig = plt.figure(figsize=(4.5, 4))
plt.scatter(preds_16, preds_24, s=14, alpha=0.7)
lims = [
    min(preds_16.min(), preds_24.min()) - 0.02,
    max(preds_16.max(), preds_24.max()) + 0.02,
]
plt.plot(lims, lims, "r--", lw=1, label="perfect agreement")
plt.xlabel("Prediction on 16³ grid")
plt.ylabel("Prediction on 24³ grid")
plt.title("Same latent systems across resolutions")
plt.legend(fontsize=8)
plt.tight_layout()
fig.show()


# %%
# .. raw:: html
#
#    <div style="margin-top: 3em;"></div>
#
# Why this is a natural FNO example
# ---------------------------------
# This example highlights two reasons neural operators are attractive in
# biomolecular electrostatics:
#
# 1. The labels come from a PDE solve rather than an arbitrary descriptor model.
# 2. Resolution invariance is genuinely useful because the same physical charge
#    configuration can be evaluated on multiple voxel grids in continuum-electrostatics
#    workflows.
#
# In a production setting, one would replace this synthetic homogeneous,
# periodic linearized-PB generator with outputs from a finite-difference PB
# solver or APBS pipeline for proteins, ligands, or protein-ligand complexes,
# while keeping the same ``FNO + ResolutionInvariantReadout`` structure.
